//! Property: TOML round-trip on `Manifest`.
//!
//! For every valid `Manifest` value generated by `arb_manifest()`, serializing
//! to TOML via `toml::to_string` and re-parsing via `Manifest::parse_toml`
//! must yield the original value.
//!
//! ## Reproducibility
//!
//! See `determinism.rs` for the env-var seeding protocol.
//!
//! ```bash
//! PROPTEST_RNG_ALGORITHM=chacha \
//! PROPTEST_RNG_SEED=42cafe13374242cafe13374242cafe13374242cafe13374242cafe13374242ca \
//! cargo nextest run -p influxdb3-plugin-schemas --test manifest_roundtrip
//! ```

#![allow(unused_crate_dependencies)]

use influxdb3_plugin_schemas::{
    Dependencies, Description, Manifest, ManifestSchemaVersion, PluginMetadata, PluginName,
    PythonRequirement, TriggerType,
};
use proptest::prelude::*;
use proptest::test_runner::{Config as ProptestConfig, RngAlgorithm};

fn arb_name() -> impl Strategy<Value = PluginName> {
    proptest::string::string_regex("[a-z][a-z0-9-]{0,15}")
        .unwrap()
        .prop_filter_map("invalid name", |s| s.parse().ok())
}

fn arb_version() -> impl Strategy<Value = semver::Version> {
    (0u64..10, 0u64..20, 0u64..20).prop_map(|(a, b, c)| semver::Version::new(a, b, c))
}

fn arb_description() -> impl Strategy<Value = Description> {
    proptest::string::string_regex("[A-Za-z][A-Za-z0-9 ]{0,49}")
        .unwrap()
        .prop_filter_map("invalid desc", |s| Description::try_new(&s).ok())
}

fn arb_trigger() -> impl Strategy<Value = TriggerType> {
    prop_oneof![
        Just(TriggerType::ProcessWrites),
        Just(TriggerType::ProcessScheduledCall),
        Just(TriggerType::ProcessRequest),
    ]
}

fn arb_triggers() -> impl Strategy<Value = Vec<TriggerType>> {
    proptest::collection::vec(arb_trigger(), 1..=3)
}

fn arb_url() -> impl Strategy<Value = Option<url::Url>> {
    prop_oneof![
        Just(None),
        proptest::string::string_regex("https://example\\.com/[a-z]{1,10}")
            .unwrap()
            .prop_map(|s| Some(url::Url::parse(&s).unwrap())),
    ]
}

fn arb_python_req() -> impl Strategy<Value = PythonRequirement> {
    prop_oneof![
        Just("requests>=2.0"),
        Just("pydantic~=2.0"),
        Just("numpy"),
    ]
    .prop_map(|s| PythonRequirement::try_new(s).unwrap())
}

fn arb_dependencies() -> impl Strategy<Value = Dependencies> {
    (
        Just(">=3.0.0".parse::<semver::VersionReq>().unwrap()),
        proptest::collection::vec(arb_python_req(), 0..=2),
    )
        .prop_map(|(database_version, python)| Dependencies {
            database_version,
            python,
        })
}

fn arb_manifest() -> impl Strategy<Value = Manifest> {
    (
        0u32..10,
        arb_name(),
        arb_version(),
        arb_description(),
        arb_triggers(),
        arb_url(),
        arb_url(),
        arb_url(),
        arb_dependencies(),
    )
        .prop_map(
            |(minor, name, version, description, triggers, homepage, repository, documentation, dependencies)| {
                Manifest {
                    manifest_schema_version: ManifestSchemaVersion::new(1, minor),
                    plugin: PluginMetadata {
                        name,
                        version,
                        description,
                        triggers,
                        homepage,
                        repository,
                        documentation,
                    },
                    dependencies,
                }
            },
        )
}

proptest! {
    #![proptest_config(ProptestConfig {
        cases: 200,
        rng_algorithm: RngAlgorithm::ChaCha,
        failure_persistence: None,
        ..ProptestConfig::default()
    })]

    #[test]
    fn toml_round_trip(m in arb_manifest()) {
        let serialized = toml::to_string(&m).expect("Manifest should serialize to TOML");
        let parsed = Manifest::parse_toml(&serialized)
            .unwrap_or_else(|e| panic!("parse_toml failed on serialized output:\n{serialized}\nerror: {e}"));
        prop_assert_eq!(m, parsed);
    }
}
