//! Property: Manifest validation idempotence (fixed-point).
//!
//! For every valid `Manifest` value generated by `arb_manifest()`, serializing
//! to TOML, parsing, re-serializing, and re-parsing must yield the exact same
//! `Manifest` *and* the exact same TOML string on the second pass as on the
//! first.
//!
//! This is strictly stronger than a single round-trip (`m == parse(serialize(m))`):
//! it asserts the **fixed point** of parse-then-serialize. If the parser
//! normalizes some field, the basic round-trip property would catch `m != m1`;
//! this property catches the case where normalization is *not idempotent* —
//! i.e., where `m1 != m2` or `s1 != s2`.
//!
//! ## Reproducibility
//!
//! See `determinism.rs` for the env-var seeding protocol.
//!
//! ```bash
//! PROPTEST_RNG_ALGORITHM=chacha \
//! PROPTEST_RNG_SEED=42cafe13374242cafe13374242cafe13374242cafe13374242cafe13374242ca \
//! cargo nextest run -p influxdb3-plugin-schemas --test manifest_validation_idempotence
//! ```

#![allow(unused_crate_dependencies)]

use influxdb3_plugin_schemas::{
    Dependencies, Description, Manifest, ManifestSchemaVersion, PluginMetadata, PluginName,
    PythonRequirement, TriggerType,
};
use proptest::prelude::*;
use proptest::test_runner::{Config as ProptestConfig, RngAlgorithm};

fn arb_name() -> impl Strategy<Value = PluginName> {
    proptest::string::string_regex("[a-z][a-z0-9-]{0,15}")
        .unwrap()
        .prop_filter_map("invalid name", |s| s.parse().ok())
}

fn arb_version() -> impl Strategy<Value = semver::Version> {
    (0u64..10, 0u64..20, 0u64..20).prop_map(|(a, b, c)| semver::Version::new(a, b, c))
}

fn arb_description() -> impl Strategy<Value = Description> {
    proptest::string::string_regex("[A-Za-z][A-Za-z0-9 ]{0,49}")
        .unwrap()
        .prop_filter_map("invalid desc", |s| Description::try_new(&s).ok())
}

fn arb_trigger() -> impl Strategy<Value = TriggerType> {
    prop_oneof![
        Just(TriggerType::ProcessWrites),
        Just(TriggerType::ProcessScheduledCall),
        Just(TriggerType::ProcessRequest),
    ]
}

fn arb_triggers() -> impl Strategy<Value = Vec<TriggerType>> {
    proptest::collection::vec(arb_trigger(), 1..=3)
}

fn arb_url() -> impl Strategy<Value = Option<url::Url>> {
    prop_oneof![
        Just(None),
        proptest::string::string_regex("https://example\\.com/[a-z]{1,10}")
            .unwrap()
            .prop_map(|s| Some(url::Url::parse(&s).unwrap())),
    ]
}

fn arb_python_req() -> impl Strategy<Value = PythonRequirement> {
    prop_oneof![
        Just("requests>=2.0"),
        Just("pydantic~=2.0"),
        Just("numpy"),
    ]
    .prop_map(|s| PythonRequirement::try_new(s).unwrap())
}

fn arb_dependencies() -> impl Strategy<Value = Dependencies> {
    (
        Just(">=3.0.0".parse::<semver::VersionReq>().unwrap()),
        proptest::collection::vec(arb_python_req(), 0..=2),
    )
        .prop_map(|(database_version, python)| Dependencies {
            database_version,
            python,
        })
}

fn arb_manifest() -> impl Strategy<Value = Manifest> {
    (
        0u32..10,
        arb_name(),
        arb_version(),
        arb_description(),
        arb_triggers(),
        arb_url(),
        arb_url(),
        arb_url(),
        arb_dependencies(),
    )
        .prop_map(
            |(minor, name, version, description, triggers, homepage, repository, documentation, dependencies)| {
                Manifest {
                    manifest_schema_version: ManifestSchemaVersion::new(1, minor),
                    plugin: PluginMetadata {
                        name,
                        version,
                        description,
                        triggers,
                        homepage,
                        repository,
                        documentation,
                    },
                    dependencies,
                }
            },
        )
}

proptest! {
    #![proptest_config(ProptestConfig {
        cases: 200,
        rng_algorithm: RngAlgorithm::ChaCha,
        failure_persistence: None,
        ..ProptestConfig::default()
    })]

    #[test]
    fn serialize_parse_is_fixed_point(m in arb_manifest()) {
        // First pass: serialize then parse.
        let s1 = toml::to_string(&m)
            .expect("Manifest should serialize to TOML (pass 1)");
        let m1 = Manifest::parse_toml(&s1)
            .unwrap_or_else(|e| panic!("parse_toml failed (pass 1):\n{s1}\nerror: {e}"));

        // Second pass: serialize the parsed result, then parse again.
        let s2 = toml::to_string(&m1)
            .expect("Manifest should serialize to TOML (pass 2)");
        let m2 = Manifest::parse_toml(&s2)
            .unwrap_or_else(|e| panic!("parse_toml failed (pass 2):\n{s2}\nerror: {e}"));

        // Fixed-point assertion: both the Manifest values and TOML strings
        // must be identical across the two passes.
        prop_assert_eq!(&m1, &m2, "Manifest diverged between pass 1 and pass 2");
        prop_assert_eq!(&s1, &s2, "Serialized TOML diverged between pass 1 and pass 2");
    }
}
