manifest_schema_version = "{{manifest_schema_version}}"

[plugin]
name = "{{name}}"
version = "0.1.0"
description = "A new write-processing plugin."
triggers = ["process_writes"]

[dependencies]
database_version = "{{database_version}}"
